#!/usr/bin/env python3
"""
Generate LaTeX table summarizing insight alignment stats

Input: JSON from experiments/rag-dynamic-db-v3/insight_eval/run_alignment_ragv3.py
Output: docs/paper/templates/tab_insight_alignment_summary.tex

Columns reported:
  n, mean(s0)±95%CI, mean(s)±95%CI, mean(Δs)±95%CI, Δs>0 ratio, Cohen's d (paired), permutation p
"""
from __future__ import annotations
from pathlib import Path
import sys
import json
import statistics
import random


def mean_ci95(xs: list[float]) -> tuple[float, float, float]:
    if not xs:
        return (float("nan"), float("nan"), float("nan"))
    m = statistics.fmean(xs)
    if len(xs) > 1:
        sd = statistics.stdev(xs)
    else:
        sd = 0.0
    se = sd / (len(xs) ** 0.5) if len(xs) else 0.0
    # normal approx 95%CI
    lo = m - 1.96 * se
    hi = m + 1.96 * se
    return m, lo, hi


def paired_perm_p(diff: list[float], iters: int = 5000, seed: int = 0) -> float:
    if not diff:
        return float("nan")
    random.seed(seed)
    obs = abs(statistics.fmean(diff))
    cnt = 0
    for _ in range(iters):
        flips = [1 if random.random() < 0.5 else -1 for _ in diff]
        md = statistics.fmean([d * s for d, s in zip(diff, flips)])
        if abs(md) >= obs:
            cnt += 1
    return (cnt + 1) / (iters + 1)


def main(argv: list[str]) -> int:
    repo_root = Path(__file__).resolve().parents[3]
    in_json = Path(argv[1]) if len(argv) > 1 else (
        repo_root / "experiments/rag-dynamic-db-v3/insight_eval/results/outputs/rag_insight_alignment_ragv3.json"
    )
    out_tex = repo_root / "docs/paper/templates/tab_insight_alignment_summary.tex"
    if not in_json.exists():
        print(f"Input JSON not found: {in_json}", file=sys.stderr)
        return 1
    js = json.loads(in_json.read_text())
    recs = js.get("records") or js.get("data") or []
    s0 = []
    s = []
    for r in recs:
        s0.append(r.get("s0"))
        s.append(r.get("s"))
    # drop Nones and align
    n = min(len([x for x in s0 if x is not None]), len([x for x in s if x is not None]))
    s0 = [x for x in s0 if x is not None][:n]
    s = [x for x in s if x is not None][:n]
    diff = [si - s0i for si, s0i in zip(s, s0)]
    m0, lo0, hi0 = mean_ci95(s0)
    m1, lo1, hi1 = mean_ci95(s)
    md, lod, hid = mean_ci95(diff)
    pos_ratio = sum(1 for d in diff if d > 0) / n if n else float("nan")
    d_cohen = (md / statistics.stdev(diff)) if n > 1 and statistics.stdev(diff) > 0 else float("nan")
    p_perm = paired_perm_p(diff)

    out_tex.parent.mkdir(parents=True, exist_ok=True)
    with out_tex.open("w") as f:
        f.write("% Auto-generated by make_insight_summary_from_json.py\n")
        f.write("\\begin{table}[H]\n\\centering\n\\small\n")
        f.write("\\begin{tabular}{lrrrrr}\\toprule\n")
        f.write("指標 & 値 & 95\\%CI下限 & 95\\%CI上限 & 備考 \\\\ \\midrule\n")
        f.write(f"n & {n} & - & - & - \\\\ \n")
        f.write(f"$s_0$ (0\,hop) & {m0:.3f} & {lo0:.3f} & {hi0:.3f} & 平均コサイン一致度 \\\\ \n")
        f.write(f"$s$ (H\,hop) & {m1:.3f} & {lo1:.3f} & {hi1:.3f} & 平均コサイン一致度 \\\\ \n")
        f.write(f"$\Delta s$ ($s-s_0$) & {md:.3f} & {lod:.3f} & {hid:.3f} & 正の割合={pos_ratio:.2f} \\\\ \n")
        f.write(f"Cohen's~d & {d_cohen:.2f} & - & - & ペア差分で算出 \\\\ \n")
        f.write(f"perm~p (two-sided) & {p_perm:.3f} & - & - & 置換検定 \\\\ \\bottomrule\n")
        f.write("\\end{tabular}\n\\caption{補足実験の循環性回避テストの要約（Opus/Haikuなどモデル依存のため例示値）。}\\label{tab:insight_summary}\n\\end{table}\n")
    print(f"✅ Wrote {out_tex}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
